const argon2 = require("argon2");

exports.seed = async function (knex) {
	await knex("users").del();
	await knex("users").insert([
		{
			password: await argon2.hash("1"),
			first_name: "John",
			last_name: "Jacob",
			rank: "Sgt",
			email: "john.jacob1@example.com",
			phone: "999-999-9999",
			organization: "Delta 1",
			crew: "Bravo",
			position: "SVO",
			permissions: "admin",
		},
		{
			password: await argon2.hash("1"),
			first_name: "Patrick",
			last_name: "Johnson",
			rank: "Cpt",
			email: "patric.johnson@example.com",
			phone: "999-999-9999",
			organization: "Delta 1",
			crew: "Front Office",
			position: "CSS",
			permissions: "admin",
		},
		{
			password: await argon2.hash("1"),
			first_name: "Frank",
			last_name: "Smith",
			rank: "SMSgt",
			email: "frank.smith@example.com",
			phone: "999-999-9999",
			organization: "Delta 1",
			crew: "Alpha",
			position: "CCH",
			permissions: "user",
		},
		{
			password: await argon2.hash("1"),
			first_name: "Sarah",
			last_name: "Young",
			rank: "TSgt",
			email: "sarah.young@example.com",
			phone: "999-999-9999",
			organization: "Delta 1",
			crew: "Charlie",
			position: "SSO",
			permissions: "user",
		},
		{
			password: await argon2.hash("1"),
			first_name: "Daniel",
			last_name: "Graves",
			rank: "SPC4",
			email: "daniel.graves@example.com",
			phone: "999-999-9999",
			organization: "Delta 1",
			crew: "Delta",
			position: "SSO",
			permissions: "user",
		},
	]);
};
