const argon2 = require("argon2");

exports.seed = async function (knex) {
	await knex("users").del();
	await knex("users").insert([
		{
			password: await argon2.hash("1"),
			first_name: "John",
			last_name: "Jacob",
			rank: "Sgt",
			email: "john.jacob1@example.com",
			phone: "808-939-9119",
			organization: "Delta 1",
			crew: "Alpha",
			position: "SVO",
			permissions: "user",
		},
		{
			password: await argon2.hash("1"),
			first_name: "Patrick",
			last_name: "Johnson",
			rank: "TSgt",
			email: "patric.johnson@example.com",
			phone: "808-939-9123",
			organization: "Delta 1",
			crew: "Bravo",
			position: "SVO",
			permissions: "user",
		},
		{
			password: await argon2.hash("1"),
			first_name: "Frank",
			last_name: "Smith",
			rank: "SMSgt",
			email: "frank.smith@example.com",
			phone: "808-939-8029",
			organization: "Delta 1",
			crew: "Charlie",
			position: "SVO",
			permissions: "user",
		},
		{
			password: await argon2.hash("1"),
			first_name: "Sarah",
			last_name: "Young",
			rank: "TSgt",
			email: "sarah.young@example.com",
			phone: "808-940-0170",
			organization: "Delta 1",
			crew: "Delta",
			position: "SVO",
			permissions: "user",
		},
		{
			password: await argon2.hash("1"),
			first_name: "Daniel",
			last_name: "Graves",
			rank: "Capt",
			email: "daniel.graves@example.com",
			phone: "808-939-5042",
			organization: "Delta 1",
			crew: "Delta",
			position: "CCO",
			permissions: "admin",
		},
		{
			password: await argon2.hash("1"),
			first_name: "Laurie",
			last_name: "Andersen",
			rank: "SPC3",
			email: "laurie.andersen@example.com",
			phone: "808-940-0101",
			organization: "Delta 1",
			crew: "",
			position: "I.T.",
			permissions: "user",
		},
		{
			password: await argon2.hash("1"),
			first_name: "Tomas",
			last_name: "Watkins",
			rank: "Sgt",
			email: "tomas.watkins@example.com",
			phone: "808-939-7300",
			organization: "Delta 1",
			crew: "",
			position: "Field Support",
			permissions: "user",
		},
	]);
};
